# -*- coding: utf-8 -*-
###############################################################################
# Name        : example_tester
# Description : A basic example on how to use the Tester class
# Notes       : Just run the script. Be sure that dataset.py is accessible,
#               that the DATASETn.TXT files are accessible, and that the
#               paths specified within DATASETn.TXT are correct. Also,
#               be sure that the example model TEST_MODEL is saved in this
#               same path. This model is generated by example_modelwrapper.py
# Author      : Antoni Burguera (antoni.burguera@uib.es)
# History     : 27-June-2019 - Creation
# Citation    : Please, refer to the README file to know how to properly cite
#               us if you use this software.
###############################################################################

from dataset import DataSet
from tester import Tester
from modelwrapper import ModelWrapper

# Load the test dataset
print('[[ LOADING DATASET 3 ]]')
dataSet=DataSet('DATASETS/DATASET3.TXT')
print('[[ DATASET LOADED ]]')

# Load the model
print('[[ LOADING THE MODEL ]]')
theModel=ModelWrapper()
theModel.load('TEST_MODEL')
print('[[ MODEL LOADED ]]')

# Creating the tester
print('[[ CREATING THE TESTER ]]')
theTester=Tester(theModel,dataSet)
print('[[ TESTER CREATED ]]')

# Computing and plotting hit ratio evolution
print('[[ COMPUTING AND PLOTTING HIT RATIO EVOLUTION ]]')
theHR,thaAUC=theTester.compute_hitratio_evolution()
theTester.plot_hitratio_evolution()
print('[[ HIT RATIO EVOLUTION COMPUTED AND PLOTTED ]]')

# Computing and printing full stats
print('[[ COMPUTING AND PRINTING FULL STATS ]]')
tp,fp,tn,fn,tdist,tloops=theTester.compute_fullstats()
print('[[ FULL STATS COMPUTED AND PRINTED ]]')